#!/bin/bash +ex

PACKAGER=/usr/bin/pkgbuild
BUILDER=/usr/bin/productbuild

if [ ! -f $PACKAGER ]; then
  echo "You need 'pkgbuild' binary to create os-x installer packages"
  exit 1
fi

if [ ! -f $BUILDER ]; then
  echo "You need 'productbuild' binary to create os-x installer packages"
  exit 1
fi

SOURCE=`pwd`
NAME="credulous"
IDENTIFIER="com.realestate-com-au.${NAME}"
VERSION=0.1.3
RELEASE=1
NVR="$NAME-$VERSION-$RELEASE"
DESTINATION="/Applications"
TMP_PKG_PATH="/tmp/credulous"
TEMP_ARTIFACT="$TMP_PKG_PATH/credulous.pkg"
ARTIFACT="osx-pkg/${NVR}.pkg"
DIST_TEMPLATE=os-x-distribution-template.xml
DIST_FILE="/tmp/os-x-distribution.xml"
RESOURCES=site
SCRIPTS="os-x-install-scripts"

echo "Removing old artifact $ARTIFACT"
rm -rf $ARTIFACT

cp $DIST_TEMPLATE $DIST_FILE

sed -i.bak -e s/IDENTIFIER/$IDENTIFIER/g $DIST_FILE
sed -i.bak -e s/NVR/$NVR/g $DIST_FILE
sed -i.bak -e s/ARTIFACT/"$NAME.pkg"/g $DIST_FILE

mkdir -p $TMP_PKG_PATH

$PACKAGER --root $SOURCE \
  --identifier $IDENTIFIER \
  --scripts $SCRIPTS \
  --version $NVR \
  --filter ".DS_Store" --filter ".git" --filter "swp" \
  --filter "os-x" --filter "osx" \
  --filter "debian" --filter "rpm" --filter "brew" \
  --install-location $DESTINATION $TEMP_ARTIFACT

$BUILDER --distribution $DIST_FILE \
  --resources $RESOURCES \
  --package-path $TMP_PKG_PATH $ARTIFACT

rm $DIST_FILE
rm $TEMP_ARTIFACT
